# Generated by Django 2.1.8 on 2019-04-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190420_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='yearbuild',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
    ]
