# Generated by Django 2.1.8 on 2019-04-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190420_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='caprate',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
