# Generated by Django 2.1.8 on 2019-04-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20190420_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listingAgent',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingOffice',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
